- .github/workflows/ci.yml
- README.md
The MSRV was incorrectly reported as 1.63 because the `rust-toolchain.toml` file was overriding the version that the check ran against.
> chore: fix msrv check

- committed.toml
It's nice to have these as a guideline, but I think it's a bit too pedantic to block PRs on these lints since we squash commits anyway.
> chore: relax committed lints

- CONTRIBUTING.md
- src/http/mod.rs
- src/lib.rs
- src/source.rs
- src/storage/adaptive.rs
- src/storage/bounded.rs
- src/storage/memory.rs
- src/storage/mod.rs
- src/storage/temp.rs
Thanks for creating this lib! For my podcast app I also want to support downloading to a permanent file. Before I implement that I went about and refactored the storage module a bit. Mostly as an exercise to familiarize myself with your code base. I think the results are worth contributing I hope they are welcome and you agree with the refactoring.
This is the phase of a two phase refactor moving writer creation to the
StorageProvide. This has two advantages:
- the new method takes self as argument therefore it is no longer possible to get multiple writers.
- shared data between reader and writer is created and distributed at
the same place (instead of the writers share going through the
reader)
> refactor: reader and writer creation now one method

- Cargo.toml
- examples/adaptive.rs
- rust-toolchain.toml
- src/source.rs
- tests/setup/mod.rs
The latest versions of hyper don't contain a high-level server struct anymore, so we'll use axum instead.
> test: use axum as file server

- src/storage/bounded.rs
- src/storage/memory.rs
We should return an explicit error if the requested buffer size is greater than `usize::MAX`.
> fix: ensure content length fits within the requested buffer

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- rust-toolchain.toml
- src/http/mod.rs
- src/http/reqwest_client.rs
- src/source.rs
- tests/integration_test.rs
Now that `1.75` has been out for a while, we should remove `async_trait` in favor of Rust's native support.
> feat: use native async traits

- Makefile.toml
- src/source.rs
Resolves #17 
This should reduce the chances of stuttering when seeking forward in the stream.
> feat: restart prefetch when seeking into a missing section

- src/lib.rs
In some cases, the stream is transferred to a different context, making it impossible to cancel from the current one. By making the download_task_cancellation_token public, you can clone the token beforehand, ensuring that cancellation remains possible regardless of the context shift
> feat: add method to get the stream cancellation token

- .github/workflows/ci.yml
- Makefile.toml
- README.md
- src/lib.rs
- src/open_dal.rs
Discovered while investigating #82 
- Doctests for extra features weren't being tested
- README examples used blocking I/O inside a Tokio task which can cause issues (especially on a single-threaded runtime)
- openDAL examples were outdated and didn't compile
> docs: fix a few problems with the examples

- Cargo.toml
- README.md
- examples/adaptive.rs
- examples/basic_http.rs
- examples/client_options.rs
- examples/custom_client.rs
- examples/from_stream.rs
- examples/infinite_stream.rs
- examples/memory_storage.rs
- examples/stream_progress.rs
- rust-toolchain.toml
- src/http/mod.rs
- src/http/reqwest_client.rs
- src/lib.rs
- src/open_dal.rs
- src/source.rs
- tests/integration_test.rs
- typos.toml
This allows for getting the underlying HTTP response body if the request fails.
> feat: return specific error types when creating a stream

- Cargo.toml
- rust-toolchain.toml
OpenDAL appears in the public API so it will help semver compatibility to allow all compatible versions to be used.
> chore(deps): expand compatible OpenDAL version range

- examples/adaptive.rs
- examples/basic_http.rs
- examples/client_options.rs
- examples/custom_client.rs
- examples/from_stream.rs
- examples/infinite_stream.rs
- examples/memory_storage.rs
- examples/retry_middleware.rs
- examples/s3.rs
- examples/stream_progress.rs
This seems to fix some issues with using Tokio's single-threaded runtime.
> fix(examples): create decoder and sink on the same thread

- .github/workflows/ci.yml
- src/lib.rs
- src/settings.rs
This changes the default behavior to only cancel the stream on drop if explicitly enabled.
> feat: add setting to cancel stream on drop

- Cargo.toml
- examples/custom_process.rs
- src/http/mod.rs
- src/lib.rs
- src/process/command_builder.rs
- src/process/mod.rs
- src/source/mod.rs
- tests/integration_test.rs
Addresses #13. Helpers for yt-dlp will follow in a subsequent PR.
> feat!: add SourceStream implementation for processes

- src/source/handle.rs
- src/storage/bounded.rs
- src/storage/memory.rs
- tests/integration_test.rs
`parking_lot`'s synchronization primitives [aren't unwind safe](https://github.com/Amanieu/parking_lot/issues/32) which can make it tricky to use the `StreamDownload` struct with FFI. However, we can use `AssertUnwindSafe` to manually mark these as safe because we should never panic while holding a mutex (if we do, that's a separate bug that should be addressed).
> feat: mark StreamDownload as UnwindSafe

- Cargo.toml
- README.md
Update `regex` because of [RUSTSEC-2022-0013](https://rustsec.org/advisories/RUSTSEC-2022-0013.html).
> chore(deps): update regex to 1.5.5

- src/lib.rs
This makes the name consistent with the other accessor methods.
> refactor!: rename get_cancellation_token to cancellation_token

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- src/http/reqwest_client.rs
- src/http/reqwest_middleware_client.rs
- src/lib.rs
- src/process/mod.rs
- src/source/handle.rs
- src/source/mod.rs
- tests/integration_test.rs
- tests/proptest.rs
- tests/setup.rs
Some dependencies require Rust 1.80 now: [build logs](https://github.com/aschey/stream-download-rs/actions/runs/13486065110/job/37677350024)
This also makes use of some new Rust features.
> refactor!: use Rust 1.80 features

- deny.toml
- src/process/ffmpeg.rs
- src/process/mod.rs
More methods for customizing command args. `-qscale:a 0` is also removed as a default arg from the ffmpeg command since it may be preferable to use the default quality settings.
> feat: more customization for command args

- Cargo.toml
- src/async_read.rs
- src/http/mod.rs
- src/http/reqwest_client.rs
- src/open_dal.rs
- src/process/mod.rs
- src/source/mod.rs
- tests/setup.rs
This PR changes `stream-download` to depend on `futures-util` directly as `futures` includes (including dependencies) a lot more than is actually used in this crate.
It *might* be possible thin it down even more, but this should reduce it at least a bit already.
PS: this does not entirely drop `futures` from the workspace due to some dev-dependencies using it, but it will for consumers of `stream-download`
> chore(deps): replace "futures" with "futures-util"

- crates/stream-download-opendal/CHANGELOG.md
- crates/stream-download-opendal/Cargo.toml
- crates/stream-download/CHANGELOG.md
- crates/stream-download/Cargo.toml
* `stream-download`: 0.17.0 -> 0.18.0 (⚠ API breaking changes)
* `stream-download-opendal`: 0.1.0
```text
--- failure feature_missing: package feature removed or renamed ---
Description:
A feature has been removed from this package's Cargo.toml. This will break downstream crates which enable that feature.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#cargo-feature-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.40.0/src/lints/feature_missing.ron
Failed in:
feature open-dal in the package's Cargo.toml
--- failure inherent_method_missing: pub method removed or renamed ---
Description:
A publicly-visible method or associated fn is no longer available under its prior name. It may have been renamed or removed entirely.
ref: …
```
> chore: release

- Makefile.toml
- examples/Cargo.toml
Feature flag some of the heavier dependencies that aren't used as frequently. It seems like `libmpv2` fails to build if it can't link against mpv's library, so that shouldn't be enabled by default.
> chore: feature flag extra dependencies in examples

- README.md
- crates/stream-download-opendal/README.md
`deprs.rs` doesn't have great support for workspaces, so it's not able to parse this repo - https://github.com/deps-rs/deps.rs/issues/174
> chore: remove deps.rs badge

- examples/Cargo.toml
Dependabot seems to be failing because some command doesn't like that the package name is `examples`:
```
updater | 2025/04/14 01:24:19 INFO <job_997503327> Handled error whilst updating tempfile: dependency_file_not_resolvable {:message=>"error: failed to load manifest for workspace member `dependabot_tmp_dir/examples`\nreferenced by workspace at `dependabot_tmp_dir/Cargo.toml`\n\nCaused by:\n  failed to parse manifest at `dependabot_tmp_dir/examples/Cargo.toml`\n\nCaused by:\n  the binary target name `examples` is forbidden, it conflicts with cargo's build directory names"}
```
> chore: change example package name

- crates/stream-download/src/lib.rs
- crates/stream-download/src/settings.rs
- crates/stream-download/src/source/handle.rs
- crates/stream-download/src/source/mod.rs
- crates/stream-download/src/storage/bounded.rs
- crates/stream-download/src/storage/memory.rs
We wait for seek operations to complete after sending each message, so there's no need to have a configurable size for the channel here.
> refactor!: remove seek_buffer_size

- Makefile.toml
- crates/stream-download/src/source/handle.rs
- crates/stream-download/src/source/mod.rs
Prevents re-requesting the entire portion of the stream after the seek position if we've already downloaded part of it.
> feat: prevent re-requesting previously downloaded stream portions during seek operations
